GET http://localhost:5288/playergames
# # User Token
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFCMDMwV1AiLCJzdWIiOiJBQjAzMFdQIiwianRpIjoiYzU4ZWJiZGIiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo1Mzg2MSIsImh0dHBzOi8vbG9jYWxob3N0OjQ0MzkxIiwiaHR0cDovL2xvY2FsaG9zdDo1Mjg4IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzEwMyJdLCJuYmYiOjE2OTUwNDM0NTUsImV4cCI6MTcwMjkwNTg1NSwiaWF0IjoxNjk1MDQzNDU4LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.enueH3MXpdnlsref7Xtt7yLwNG05LaTsHb0l_zmQWTw 
# Admin Token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFCMDMwV1AiLCJzdWIiOiJBQjAzMFdQIiwianRpIjoiNmFmZDBiMTQiLCJyb2xlIjoiYWRtaW4iLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo1Mzg2MSIsImh0dHBzOi8vbG9jYWxob3N0OjQ0MzkxIiwiaHR0cDovL2xvY2FsaG9zdDo1Mjg4IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzEwMyJdLCJuYmYiOjE2OTUxMzE1OTUsImV4cCI6MTcwMjk5Mzk5NSwiaWF0IjoxNjk1MTMxNTk3LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.28S-v-QJhIj2qpOdistaDisrXH3TQlp59tZkBShXWb0 